// app/layout.tsx
import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  contacticons,
  leftverticaline,
}: Readonly<{
  children: React.ReactNode;
  contacticons: React.ReactNode;
  leftverticaline: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className=" flex flex-row justify-between items-center">
        {children}
        {contacticons}
        {leftverticaline}
      </body>
    </html>
  );
}
